### ISSUE TITLE
Example: Cannot access the state with Zustand

### ISSUE THREAD

**Issue by BrantalikP** [HackYourFuture-CPH/class-25-ironside#16]
- Right now I am having an error when I try to access a zustand state from login screen
![Screenshot 2023-09-29 at 7 34 40](https://github.com/HackYourFuture-CPH/class-25-ironside/assets/48878547/aa181056-bf1e-4d09-9113-389888a5cda8)

my branch: [ttps://github.com/HackYourFuture-CPH/class-25-ironside/tree/test-branch](https://github.com/HackYourFuture-CPH/class-25-ironside/tree/test-branch)

file: `frontend/src/pages/login/Login.tsx`

```
function LoginPage() {
  const [email, setEmail] = useState<string>('');
  const [password, setPassword] = useState<string>('');
  const [error, setError] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);
  const { login, currentUser } = useContext(AuthContext);
  const user = useUserStore((state) => state.user);

  const navigate = useNavigate();
```

**Comment by hamoudi-hamoudi** [comment]
Is this now or 3 weeks ago ?

**Comment by BrantalikP** [comment]
3 weeks ago :D This was example how to write issues
